In [37]:
import numpy as np

### We will explore principle of Neural Networks for a two layers networks

#### Data set - Columns of X and Y are data points and corresponding labels


In [38]:
X = X = np.array([[0, 1, 2],
              [0, 1, 2]])
Y = np.array([[0, 1, 0]])

#### Initial `weights` matrix

In [39]:
W1 = np.array([[1, -1], [0, 0]])
W1

array([[ 1, -1],
       [ 0,  0]])

In [40]:
W0 = np.array([[-0.5], [1.5]])
W0.shape

(2, 1)

#### Computing `pre-activation` matrix Z = W1.T @ X 

In [41]:
X.shape

(2, 3)

In [42]:
Z = np.dot(W1.T, X) + W0

In [43]:
Z

array([[-0.5,  0.5,  1.5],
       [ 1.5,  0.5, -0.5]])

In [44]:
X = np.concatenate([X, np.ones((1, X.shape[1]))], axis=0)

In [45]:
X

array([[0., 1., 2.],
       [0., 1., 2.],
       [1., 1., 1.]])

In [47]:
W1 = np.concatenate([W1, W0.T], axis=0)

In [48]:
W1

array([[ 1. , -1. ],
       [ 0. ,  0. ],
       [-0.5,  1.5]])

In [49]:
Z = np.dot(W1.T, X)

In [50]:
Z

array([[-0.5,  0.5,  1.5],
       [ 1.5,  0.5, -0.5]])

#### Applying step function on this result give us 

In [66]:
#Z1 = [0, 1, 1]
#Z2 = [1, 1, 0]